name: Veracode Upload and Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  veracode_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del c칩digo
        uses: actions/checkout@v3

      - name: Comprimir c칩digo fuente
        run: |
          zip -r veracode_package.zip . -x "*.git*" "__pycache__/*"

      - name: Subir c칩digo a Veracode y ejecutar an치lisis
        uses: veracode/Veracode-uploadandscan-action@master
        with:
        with:
          appname: 'company-management-app_UNIE'
          createprofile: true
          filepath: 'veracode_package.zip'
          version: '${{ github.run_id }}'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY_SECRET }}'