name: Veracode SAST + SCA

on: [push, pull_request]

jobs:
  veracode_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del c칩digo
        uses: actions/checkout@v3

      - name: Instalar Veracode CLI
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode version

      - name: An치lisis SAST (c칩digo fuente)
        env:
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
        run: |
          ./veracode scan --source . --type static --fail-on-policy true

      - name: An치lisis SCA (dependencias)
        env:
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
        run: |
          ./veracode sbom --source . --format cyclonedx-json
          ./veracode scan --type sca --fail-on-policy true
  